SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Sprite Move with Walls Example"

# player
MOVEMENT_SPEED = 5
JUMP_SPEED = 14
SPRITE_SCALING = 0.5
GRAVITY = .9 * SPRITE_SCALING

# enemy
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)
